name: Compile RimWorld Mod
on: [push, workflow_dispatch]
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Compile Mod
      run: |
        cd Source/RunAndGunCEFix
        dotnet build --configuration Release --no-restore
        
    - name: Upload Compiled DLL
      uses: actions/upload-artifact@v3
      with:
        name: RunAndGunCEFix-Mod
        path: Source/RunAndGunCEFix/bin/Release/RunAndGunCEFix.dll
